image:
  file: .gitpod.Dockerfile
  
tasks:
  - before: export DANGEROUSLY_DISABLE_HOST_CHECK=true 
  - command: export DANGEROUSLY_DISABLE_HOST_CHECK=true && cd client && npm install && npm start
  - command: mvn install -DskipTests=false && mvn liberty:dev
  
