image:
  file: .gitpod.Dockerfile
  
tasks:
  - before: export DANGEROUSLY_DISABLE_HOST_CHECK=true 
  - init: cd client && npm install && npm start
  - init: mvn install -DskipTests=false && mvn liberty:dev
  
